### ISSUE TITLE
Please add support global templateSettings

### ISSUE THREAD

**Issue by gogocat** [superRaytin/underscore.template#1]
Can you expose the _ (underscore) object to window / global
to allow change templateSetting globally.

eg:
_.templateSettings.interpolate = /{{(.+?)}}/g;

**Comment by superRaytin** [comment]
@gogocat now you can access `_` via:

``` js
var UnderscoreTemplate = require('underscore.template');
var _ = UnderscoreTemplate._;
_.templateSettings.interpolate = /{{(.+?)}}/g;
```

**Comment by gogocat** [comment]
Thanks Leon.

FYI, i using this template with morphdom.
https://github.com/patrick-steele-idem/morphdom

Works very well.

Adam
